---
- name: ios show commands
  hosts: ios
  gather_facts: no

  vars:
  - ansible_command_timeout: 60
  
  tasks:
  - name: gather ios facts all
    cisco.ios.ios_facts:
      gather_subset: all
  
  - name: save running-config to localfile
    copy:
      content:  "{{ ansible_net_config }}"
      dest: "./config_{{ ansible_net_hostname }}_{{ now(False, '%Y%m%d_%H%M%S') }}.txt"
